services:
  airflow_init:
    image: littlest-airflow:latest
    container_name: airflow-init
    command: [ "airflow", "db", "migrate" ]
    depends_on:
      - db
    volumes:
      - airflow-logs:/home/littlest-airflow/logs

  webserver:
    image: littlest-airflow:latest
    command: [ "airflow", "webserver" ]
    container_name: webserver
    ports:
      - "8080:8080"
    depends_on:
      - airflow_init
    volumes:
      - airflow-logs:/home/littlest-airflow/logs

  scheduler:
    image: littlest-airflow:latest
    command: [ "airflow", "scheduler" ]
    container_name: scheduler
    depends_on:
      - airflow_init
    volumes:
      - airflow-logs:/home/littlest-airflow/logs

  worker:
    image: littlest-airflow:latest
    command: [ "airflow", "celery", "worker" ]
    container_name: worker_1
    depends_on:
      - db
    volumes:
      - airflow-logs:/home/littlest-airflow/logs

  flower:
    image: littlest-airflow:latest
    command: [ "airflow", "celery", "flower" ]
    container_name: flower
    volumes:
      - airflow-logs:/home/littlest-airflow/logs
    ports:
      - "5555:5555"
    depends_on:
      - worker
      - db

  db:
    image: postgres:16.4-bullseye
    container_name: postgres-server
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-server
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres-data:
  airflow-logs:


