services:
  airflow_init:
    image: littlest-airflow:latest
    container_name: airflow-init
    command: [ "airflow", "db", "migrate" ]
    depends_on:
      - db

  webserver:
    image: littlest-airflow:latest
    command: [ "airflow", "webserver" ]
    container_name: webserver
    ports:
      - "8080:8080"
    depends_on:
      - db
      - airflow_init

  # scheduler:
  #   image: littlest-airflow:latest
  #   container_name: scheduler
  #   environment:
  #     AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@db:5432/postgres
  #     AIRFLOW__CORE__EXECUTOR: LocalExecutor
  #     AIRFLOW__CORE__LOAD_EXAMPLES: "True"
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./dags:/opt/airflow/dags
  #     - ./logs:/opt/airflow/logs
  #     - ./plugins:/opt/airflow/plugins

  # worker:
  #   image: littlest-airflow:latest
  #   container_name: worker
  #   environment:
  #     AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@db:5432/postgres
  #     AIRFLOW__CORE__EXECUTOR: LocalExecutor
  #     AIRFLOW__CORE__LOAD_EXAMPLES: "True"
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./dags:/opt/airflow/dags
  #     - ./logs:/opt/airflow/logs
  #     - ./plugins:/opt/airflow/plugins

  db:
    image: postgres:16.4-bullseye
    container_name: postgres-server
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-server
    ports:
      - "5672:5672"
      - "15672:15672"
volumes:
  postgres-data:


